mode: development
media_root:: media
media_url: /media
base_url: /
template: hyde.ext.jinja2
meta:
    author: Lakshmi Vyas
    twitter: http://twitter.com/lakshmivyas
    about: |
        Ringce is a small software company focussed on
        simple, useful and beautiful software, inside &
        outside. Ringce is based out of an equally simple,
        useful and beautiful city of Chennai.

        The name Ringce is derived from [The book of five rings][FR] by
        [Miyamoto Mushashi][MM].
        [MM]:http://en.wikipedia.org/wiki/Miyamoto_Musashi
        [FR]:http://www.amazon.com/Book-Five-Rings-Miyamoto-Musashi/dp/1590308913

    footnote: |
        Sculpted with [Slammer][]. Smelted with [Hyde][]. Copyright &copy; Ringce,&nbsp;2008 &mdash;&nbsp;2011.
        [Slammer]: /slammer
        [Hyde]: /hyde


plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.less.LessCSSPlugin
    - hyde.ext.plugins.blockdown.BlockdownPlugin
    - hyde.ext.plugins.sorter.SorterPlugin
less:
    app: ~/local/bin/lessc
markdown:
    extensions:
        - def_list