media_root:: media
media_url: /media
base_url: /
template: hyde.ext.jinja2
meta:
    author: Lakshmi Vyas
    twitter: http://twitter.com/lakshmivyas
    footnote: |
context:
    data:
        in_production_mode: true
plugins:
    - hyde.ext.plugins.folders.FlattenerPlugin
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.less.LessCSSPlugin
    - hyde.ext.plugins.blockdown.BlockdownPlugin
    - hyde.ext.plugins.sorter.SorterPlugin
    - hyde.ext.plugins.grouper.GrouperPlugin
    - hyde.ext.plugins.markings.MarkingsPlugin
    - hyde.ext.plugins.markings.ReferencePlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
less:
    app: ~/local/bin/lessc
markdown:
    extensions:
        - def_list
        - headerid