application: ringceweb
version: 1
runtime: python
api_version: 1

handlers:
- url: /sitemap.xml
  static_files: sitemap.xml
  upload: sitemap.xml
  
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
      
- url: /(ringce\.html)?
  static_files: ringce.html
  upload: ringce.html
  
- url: /favicon.ico
  static_files: media/images/favicon.ico
  upload: media/images/favicon.ico

- url: /media
  static_dir: media
  
- url: /media/css/(.*)\.syn
  static_files: media/css/\1.syn
  mime_type: text/css
  upload: media/css/(.*)\.syn

- url: /(.*?)/([^\.\/]*).xml
  static_files: \1/\2.xml
  upload: (.*?)/([^\.\/]*).xml

- url: /(.*?)/([^\.\/]*).html
  static_files: \1/\2.html 
  upload: (.*?)/([^\.\/]*).html

- url: /([^\.\/]*)/?
  static_files: \1/\1.html 
  upload: ([^\.\/]*)/([^\.\/]*).html

- url: /(.*?)/([^\.\/]*)/?
  static_files: \1/\2/\2.html 
  upload: (.*?)/([^\.\/]*)/([^\.\/]*).html
